# Generated by Django 3.0.8 on 2020-08-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_auto_20200813_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_project.Sections'),
        ),
        migrations.AddField(
            model_name='students',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
