# Generated by Django 3.0.8 on 2020-08-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0005_auto_20200813_0934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='programs',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sections',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='SupMessageAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_admin', models.TextField()),
                ('message_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveSupervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.Supervisor')),
            ],
        ),
    ]
