# Generated by Django 3.0.8 on 2020-08-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0006_auto_20200816_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudMessageAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_message', models.TextField()),
                ('admin_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.Students')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyProjectApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_date', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=225)),
                ('abstract', models.TextField()),
                ('conclusion', models.TextField()),
                ('approval_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_project.Students')),
            ],
        ),
    ]
